= Quarkus OpenFGA Client

include::./includes/attributes.adoc[]

== Overview

The **Quarkus OpenFGA Client** extension provides a reactive client for accessing https://openfga.dev[OpenFGA]
instances. Additionally, it is the client that powers the
https://github.com/quarkiverse/quarkus-zanzibar#OpenFGA-Connector[Quarkus Zanzibar - OpenFGA Connector] to provide
Find Grained Authorization for Quarkus applications.


== Installation

To use this extension,
you need to add the `io.quarkiverse.openfga:quarkus-openfga-client` extension first to your build file.

For instance, with Maven, add the following dependency to your POM file:

[source,xml,subs=attributes+]
----
<dependency>
    <groupId>io.quarkiverse.openfga</groupId>
    <artifactId>quarkus-openfga-client</artifactId>
    <version>{project-version}</version>
</dependency>
----

Or with Gradle, add the dependency to your `build.gradle` or `build.gradle.kts` file:

[source,kotlin,subs=attributes+]
----
implementation("io.quarkiverse.openfga:quarkus-openfga-client:{project-version}")
----

[[configuration]]
== Configuration

The extension requires two configuration properties to be defined at startup to define what instance and store are
targeted by the client. The `url` property selects the scheme, host and, optionally, the port of the OpenFGA instance.
While `store` determines which authorization store is targeted; ***it can be referenced by store id or name***.

[source,properties]
----
quarkus.openfga.url=http://localhost:80
quarkus.openfga.store=my-app-authz
# Optional authorization model id
#quarkus.openfga.authorization-model-id=11G22H33I44J55K66L77M88N99
----

=== Credentials

The client supports configuring Pre-Shared Key and dynamic OIDC credentials for authentication, in addition to the
default of providing no credentials.

To enable a specific credentials method, set the `quarkus.openfga.credentials.method` property to the desired
method, either `none`, `preshared`, or `oidc`.
If no credentials method is explicitly configured, the client will default to `none` and provide no credentials.

[source,properties]
----
quarkus.openfga.credentials.method=preshared
----

NOTE: The selected credentials method must be configured in the OpenFGA instance separately.

==== Pre-Shared Key

When using the pre-Shared Key method, the client requires the `quarkus.openfga.credentials.preshared.key` property to
be set to a pre-shared key configured in the OpenFGA instance.

[source,properties]
----
quarkus.openfga.credentials.method=preshared
quarkus.openfga.credentials.preshared.key=my-secret-key # <1>
----
<1> (*required*) A pre-shared key configured in the OpenFGA instance.

==== OIDC

When using the OIDC method, the client requires a number of properties to be set that are provided by
the OIDC provider.

[source,properties]
----
quarkus.openfga.credentials.method=oidc
quarkus.openfga.credentials.oidc.client-id=my-client-id # <1>
quarkus.openfga.credentials.oidc.client-secret=my-client-secret # <2>
quarkus.openfga.credentials.oidc.audience=https://my-audience # <3>
quarkus.openfga.credentials.oidc.token-issuer=https://my-oidc-provider.com # <4>
quarkus.openfga.credentials.oidc.token-issuer-path=/oauth2/token # <5>
----
<1> (*required*) Client ID provided by the OIDC provider.
<2> (*required*) Client Secret provided by the OIDC provider.
<3> (*required*) Audience provided by the OIDC provider.
<4> (*required*) Token issuer URL provided by the OIDC provider, this can be a full URL to the token issuer endpoint
    or just the base URL of the OIDC provider.
<5> (*optional*) The OIDC provider's token issuer path, which is resolved against the `token-issuer` property to
    determine the full token issuer URL. This is only required if the token issuer URL does not include the token
    issuer path.

There are additional properties that can be provided to configure the OIDC client, these are detailed in the
link:#extension-configuration-reference[Extension Configuration Reference].

[[configuration-devservices]]
=== DevServices

The extension supports Quarkus's DevServices and will start and configure a local OpenFGA in `dev` and `test` if no
`url` configuration property is provided. Additionally it will automatically create and configure an authorization
store in the server.

==== Configuration

To enable DevServices, set the `quarkus.openfga.devservices.enabled` property to `true`, which is enabled for the
`dev` and `test` profiles by default.
This will start a local OpenFGA instance to run *unauthenticated*, initialize an empty store and configure the
client to connect to the local instance.

==== Startup Initialization

In addition to starting and creating an authorization store, an authorization model and/or tuples can be loaded
into the store on startup by providing the appropriate configuration properties.

[source,properties]
----
quarkus.openfga.devservices.enabled=true
quarkus.openfga.devservices.authorization-model-location=auth-model.json # <1>
quarkus.openfga.devservices.authorization-tuples-location=auth-tuples.json # <2>
----
<1> (*optional*) The location of the authorization model JSON file to load into the store.
<2> (*optional*) The location of the authorization tuples JSON file to load into the store.

NOTE: The authorization model and tuples JSON files are loaded from the classpath by default, but can be loaded from a
filesystem path by prefixing the location with `filesystem:`. As in, `filesystem:/path/to/auth-model.json`.


===== Authentication

For most development and test use cases an unauthenticated configuration is sufficient.
However, for simulating a production  environment, the DevServices instance can be configured to use a
specific authorization method by setting the `quarkus.openfga.devservices.authentication.method` property to
the desired method, either `none`, `preshared`, or `oidc`.

Here is an example configuration for using the pre-shared key method:

[source,properties]
----
quarkus.openfga.devservices.authentication.method=preshared
quarkus.openfga.devservices.authentication.preshared.keys=my-secret-key # <1>
----
<1> (*required*) A pre-shared key to use for authentication.
    This can be a single key or a comma-separated list of keys.

This will configure the DevServices instance to use the pre-shared key method for authentication and pass
the provided key(s) to the instance.
Additionally, the client will be configured to use the same method and one of the provided keys to authenticate
with the DevServices instance.

NOTE: For OIDC, the OpenFGA requires you to use a separate OIDC provider to authenticate the DevServices instance.
See the link:#extension-configuration-reference[Extension Configuration Reference] for the specific configuration
properties available.

[[basic-usage]]
== Basic Usage

Adding the `quarkus-openfga-client` extension to your project defines clients beans `OpenFGAClient` that are configured to access the OpenFGA instance configured in `application.properties`.

=== Clients

The extension provides three injectable clients for accessing the configured instance and store.

`OpenFGAClient`:: Main client for accessing the OpenFGA instance.
`StoreClient`:: Access authorization store configured via `quarkus.openfga.store-id`
`AuthorizationModelsClient`:: Manage (list, create, delete) authorization models and create `AuthorizationModelClient` instances for accessing a specific model.
`AuthorizationModelClient`:: Access authorization model configured via `quarkus.openfga.authoriztion-model-id` or the default model if none is configured.

== Examples

=== Write a Relationship Tuple

[source,java]
----
class ExampleTupleWriter {

    @Inject
    StoreClient storeClient;

    void write() {
        var authModelClient = storeClient.authorizationModels().defaultModel();
        authModelClient.write(TupleKey.of("thing:1", "reader", "user:me"));
    }
}
----

==== Check Access for a Relationship Tuple

[source,java]
----
class Example {

    @Inject
    AuthorizationModelClient defaultAuthModelClient;

    void write() {
        if (defaultAuthModelClient.check(TupleKey.of("thing:1", "reader", "user:me"))) {
            System.out.println("Allowed!");
        }
    }
}
----

[[extension-configuration-reference]]
== Extension Configuration Reference

include::includes/quarkus-openfga.adoc[leveloffset=+1, opts=optional]
